[FIX] fix CI checks;

diff --git a/.github/workflows/ci-go-lint.yml b/.github/workflows/ci-go-lint.yml
--- a/.github/workflows/ci-go-lint.yml
+++ b/.github/workflows/ci-go-lint.yml
@@ -1,5 +1,9 @@
 name: ci-go-lint
 on:
+  workflow_run:
+    workflows: ["ci-security-scanner-checks"]
+    types:
+      - completed
   push:
     branches:
       - main
@@ -14,7 +18,13 @@ jobs:
     name: lint
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v4
+      - name: Fail if Previous workflow failed
+        if: ${{ github.event.workflow_run.conclusion != 'success' }}
+        run: |
+          echo "Security Scan failed. Failing CI pipeline."
+          exit 1
+      - name: Checkout Code
+        uses: actions/checkout@v4
       - name: Get Go Version
         run: |
           #!/bin/bash
